### ISSUE TITLE
Написать код для общения приложения с бд

### ISSUE THREAD

**Issue by kirillTal** [kirillTal/QR-own#14]
Необходимо написать для добавления информации об отсканированном штрих коде. Пример работы - 
Пользователю необходимо присвоить штрих коду определенную информацию: 
1. Пользователь переходит в окно Добавления информации в бд. 
2. Пользователь сканирует штрих код.
3. В специальное окно пользователь вносит информацию для этого штрих кода.
4. По нажатию кнопки отправки, информация вносится в бд.

**Comment by kungrem23** [comment]
пели немецкие песни с сеньорами
